FROM node:22.14.0-alpine

WORKDIR /app
ARG DATABASE_URL
ENV DATABASE_URL=$DATABASE_URL
COPY package*.json ./
RUN npm install

COPY . .

RUN npx prisma generate

EXPOSE 3003

CMD ["npm", "run", "start:dev"]
