FROM node:22.14.0-alpine

WORKDIR /app

ARG DATABASE_URL=postgresql://award:award@db:5432/award?schema=public
ENV DATABASE_URL=$DATABASE_URL

COPY package*.json ./
RUN npm ci --legacy-peer-deps

COPY . .

RUN npx prisma generate

EXPOSE 3001

CMD ["npm", "run", "start:dev"]
